Repository team-yaza/mozi-client, pull requests merged in 2022-07, with the labels that each got.

#10 chore: prettier 설정 추가
  .prettierrc
Labels: chore

#20 chore: husky
  .husky/pre-commit
  package.json
  yarn.lock
Labels: chore

#21 chore: cypress
  cypress.config.ts
  cypress/e2e/1-getting-started/todo.cy.js
  cypress/e2e/2-advanced-examples/actions.cy.js
  cypress/e2e/2-advanced-examples/aliasing.cy.js
  cypress/e2e/2-advanced-examples/assertions.cy.js
  cypress/e2e/2-advanced-examples/connectors.cy.js
  cypress/e2e/2-advanced-examples/cookies.cy.js
  cypress/e2e/2-advanced-examples/cypress_api.cy.js
  cypress/e2e/2-advanced-examples/files.cy.js
  cypress/e2e/2-advanced-examples/local_storage.cy.js
  cypress/e2e/2-advanced-examples/location.cy.js
  cypress/e2e/2-advanced-examples/misc.cy.js
  cypress/e2e/2-advanced-examples/navigation.cy.js
  cypress/e2e/2-advanced-examples/network_requests.cy.js
  cypress/e2e/2-advanced-examples/querying.cy.js
  cypress/e2e/2-advanced-examples/spies_stubs_clocks.cy.js
  cypress/e2e/2-advanced-examples/traversal.cy.js
  cypress/e2e/2-advanced-examples/utilities.cy.js
  cypress/e2e/2-advanced-examples/viewport.cy.js
  cypress/e2e/2-advanced-examples/waiting.cy.js
  cypress/e2e/2-advanced-examples/window.cy.js
  cypress/e2e/app.cy.ts
  cypress/e2e/spec.cy.ts
  cypress/fixtures/example.json
  cypress/support/commands.ts
  cypress/support/e2e.ts
  package.json
  tsconfig.json
  yarn.lock
Labels: chore

#27 feat: react-query 적용
  package.json
  pages/_app.tsx
  pages/index.tsx
  shared/utils/queryClient.ts
  yarn.lock
Labels: feature

#31 feat: main page layout
  package.json
  pages/_app.tsx
  pages/index.test.tsx
  pages/index.tsx
  shared/api/apiClient.ts
  styles/globalStyle.ts
  yarn.lock
Labels: refactor, feature, style, test

#39 feat: todo list
  cypress/e2e/app.cy.ts
  pages/index.tsx
  shared/api/apiClient.ts
  shared/api/todoAPI.ts
  tests/pages/index.test.tsx
Labels: feature

#41 feat: 할일 삭제 버튼 및 삭제 요청
  pages/index.tsx
Labels: feature

#43 refactor: main page api logic
  pages/index.tsx
  shared/api/todoAPI.ts
Labels: refactor

#46 feature: side bar
  components/sidebar/index.tsx
  components/sidebar/menu/index.tsx
  components/sidebar/menu/style.tsx
  components/sidebar/styled.tsx
  pages/index.tsx
  shared/types/menu.ts
Labels: refactor, feature

#38 chore: Continuous Integration
  .eslintrc.js
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/RFC.md
  .github/pull_request_template.md
  .github/workflows/ci.yml
  cypress/e2e/spec.cy.ts
  jest.config.js
  package.json
  pages/index.tsx
  setupTests.ts
  tsconfig.json
Labels: chore, test

#47 test: TodoSubmitForm 테스트 코드 작성
  components/index/TodoSubmitForm/index.test.tsx
  components/sidebar/index.tsx
  package.json
  tsconfig.json
  yarn.lock
Labels: refactor, chore, test

#50 refactor: index Page
  components/sidebar/index.tsx
  components/sidebar/menu/index.tsx
  components/sidebar/styles.tsx
  shared/types/menu.ts
Labels: refactor, style

#54 feat: Recoil 적용
  components/index/TodoList/index.tsx
  components/index/TodoSubmitForm/index.test.tsx
  components/index/TodoSubmitForm/index.tsx
  jest.config.js
  package.json
  pages/_app.tsx
  pages/index.tsx
  store/todo/atom.ts
  tests/pages/index.test.tsx
  yarn.lock
Labels: refactor, feature

#55 refactor: Main Page
  .eslintrc.js
  components/index/TodoList/index.tsx
  components/index/TodoList/styles.tsx
  components/index/TodoListItem/index.tsx
  components/index/TodoListItem/styles.tsx
  components/index/TodoSubmitForm/index.test.tsx
  components/index/TodoSubmitForm/index.tsx
  cypress/tsconfig.json
  jest.config.js
  jest.setup.js
  next.config.js
  package.json
  pages/index.tsx
  shared/api/todoApi.ts
  testUtils.tsx
  tests/pages/index.test.tsx
  tsconfig.json
  yarn.lock
Labels: bug, chore, test

#53 style: Main Page UI 레이아웃 구성
  components/index/Header/index.test.tsx
  components/index/Header/index.tsx
  components/index/Header/styles.tsx
  components/index/TodoList/styles.tsx
  components/index/TodoListItem/index.tsx
  components/index/TodoListItem/styles.tsx
  components/index/TodoSubmitForm/index.tsx
  components/index/TodoSubmitForm/styles.tsx
  pages/index.tsx
  styles/utils.ts
Labels: refactor, style

#58 chore: issue template 수정
  .github/ISSUE_TEMPLATE/basic-issue-template.md
  .github/pull_request_template.md
Labels: chore

#57 chore: eslint next plugin 추가
  .eslintrc.js
  package.json
  yarn.lock
Labels: chore

#65 feat: Storybook
  .eslintrc.js
  .storybook/main.js
  .storybook/preview.js
  package.json
  stories/Button.stories.tsx
  stories/Button.tsx
  stories/Header.stories.tsx
  stories/Header.tsx
  stories/Introduction.stories.mdx
  stories/Page.stories.tsx
  stories/Page.tsx
  stories/assets/code-brackets.svg
  stories/assets/colors.svg
  stories/assets/comments.svg
  stories/assets/direction.svg
  stories/assets/flow.svg
  stories/assets/plugin.svg
  stories/assets/repo.svg
  stories/assets/stackalt.svg
  stories/button.css
  stories/header.css
  stories/page.css
  yarn.lock
Labels: feature

#68 chore: 폴더 이름 수정 및 테스트 폴더 분리
  components/common/Sidebar/SideBarMenu/index.tsx
  components/common/Sidebar/SideBarMenu/styles.tsx
  components/common/Sidebar/index.tsx
  components/common/Sidebar/styles.tsx
  jest.config.js
  pages/index.tsx
  tests/components/index/Header/index.test.tsx
  tests/components/index/TodoSubmitForm/index.test.tsx
  tsconfig.json
Labels: chore, test

#73 feat: map 페이지에 naver 지도 연동
  .gitignore
  hooks/useMap.ts
  package.json
  pages/map/index.tsx
  tsconfig.json
  yarn.lock
Labels: feature

#76 feat: register service worker
  .eslintrc.js
  pages/_app.tsx
  public/sw.js
Labels: feature

#79 refactor: 메인페이지 컴포넌트들 리액트 쿼리와 의존성 제거
  components/index/TodoList/index.test.tsx
  components/index/TodoList/index.tsx
  components/index/TodoListItem/index.tsx
  components/index/TodoSubmitForm/index.tsx
  hooks/apis/todo/useTodoMutation.ts
  hooks/useInput.ts
  jest.config.js
  pages/index.tsx
  services/apis/todo.ts
  shared/types/todo.ts
  utils/fetcher.ts
Labels: refactor, feature

#82 feat: useDebounce hook
  hooks/useDebounce/index.test.tsx
  hooks/useDebounce/index.ts
Labels: feature

#83 Yarn cache 적용
  .github/workflows/ci.yml
Labels: chore

#84 fix: todo update 버그 수정
  components/index/TodoListItem/index.tsx
Labels: bug

#86 refactor: TodoListItem 컴포넌트
  components/index/TodoList/index.test.tsx
  components/index/TodoListItem/index.test.tsx
  components/index/TodoListItem/index.tsx
  components/index/TodoListItem/styles.tsx
Labels: refactor, test

#88 refactor: TodoListItem 컴포넌트
  components/index/TodoListItem/index.tsx
  hooks/useDebounce/index.test.ts
  shared/types/service-worker.d.ts
  worker/index.ts
Labels: refactor

#90 feat: 사용자 위치 마킹
  hooks/useMap.ts
  pages/map/index.tsx
  shared/utils/getCurrentPosition.ts
Labels: feature

#91 feat: SideBar 넓이 조절 기능 및 스토리북 작성
  .storybook/main.js
  .storybook/preview.js
  components/common/Sidebar/index.stories.tsx
  components/common/Sidebar/index.tsx
  components/common/Sidebar/styles.tsx
  hooks/useDrag/index.ts
  package.json
  pages/index.tsx
  styles/globalStyle.ts
  tests/pages/index.test.tsx
  yarn.lock
Labels: refactor, feature, style

#98 test: TodoSubmitForm 컴포넌트 테스트 코드 추가
  components/index/TodoList/index.test.tsx
  components/index/TodoSubmitForm/index.test.tsx
  pages/index.tsx
Labels: test

#101 fix: SideBar 넓이가 바뀔 때마다 styled-component에 의해 클래스 추가되는 버그 수정
  components/common/Sidebar/index.tsx
  components/common/Sidebar/styles.tsx
Labels: bug, refactor

#102 fix: utils 폴더 shard 하위 경로로 이동
  services/apis/todo.ts
  shared/utils/fetcher.ts
Labels: refactor

#104 feat: TodoListItem 스토리북 작성 및 CSS 개선
  components/index/TodoListItem/index.stories.tsx
  components/index/TodoListItem/index.tsx
  components/index/TodoListItem/styles.tsx
  jest.config.js
  public/assets/svgs/check.svg
Labels: feature, style

#107 feature: 주기적으로 근접 장소 확인 및 알림
  components/index/TodoListItem/index.tsx
  hooks/location/useLocation.ts
  hooks/location/useLocationRef.ts
  hooks/useMap.ts
  pages/_app.tsx
  pages/map/index.tsx
  shared/types/location.ts
  shared/utils/getCurrentPosition.ts
  shared/utils/getDistance.ts
Labels: feature

#108 feat: useTodoListQuery
  hooks/apis/todo/useTodoListQuery.ts
  pages/index.tsx
  shared/types/common.ts
Labels: feature
