Repository team-yaza/mozi-client, pull requests merged in 2022-08, with the labels that each got.

#111 feat: useOnClickOutside
  hooks/useOnClickOutside/index.test.ts
  hooks/useOnClickOutside/index.ts
Labels: feature

#116 feat: 장소를 입력받기 위해 Todo 클릭시 공간 늘어나는 기능 구현
  components/index/TodoListItem/index.tsx
  components/index/TodoListItem/styles.tsx
  hooks/useOnClickOutside/index.test.ts
  hooks/useOnClickOutside/index.ts
  pages/_app.tsx
  services/apis/todo.ts
Labels: feature

#117 feat: ErrorBoundary
  components/common/ErrorBoundary/index.test.tsx
  components/common/ErrorBoundary/index.tsx
Labels: feature

#118 feat: Todo 클릭시 지도 띄우기
  components/index/MapModal/index.tsx
  components/index/MapModal/styles.tsx
  components/index/TodoListItem/index.tsx
  components/index/TodoListItem/styles.tsx
  hooks/useMap.ts
  pages/_app.tsx
  pages/map/index.tsx
Labels: feature

#119 feat: useLocalForage
  hooks/useLocalForage/index.test.ts
  hooks/useLocalForage/index.ts
  package.json
  yarn.lock
Labels: feature

#120 style: TodoListItem 하위 컴포넌트 네이밍 개선
  components/index/TodoListItem/index.tsx
  components/index/TodoListItem/styles.tsx
  shared/types/todo.ts
Labels: style

#121 refactor: TodoListItem
  components/index/TodoList/index.test.tsx
  components/index/TodoList/index.tsx
  components/index/TodoListItem/index.stories.tsx
  components/index/TodoListItem/index.test.tsx
  components/index/TodoListItem/index.tsx
  hooks/apis/todo/useTodoMutation.ts
  pages/index.tsx
  services/apis/todo.ts
  shared/types/todo.ts
Labels: refactor

#124 feat: 지도에서 장소데이터 업데이트
  components/index/MapModal/index.tsx
  components/index/MapModal/styles.tsx
  components/index/TodoList/index.tsx
  components/index/TodoListItem/index.tsx
  components/map/SearchInput/index.tsx
  hooks/apis/todo/useTodoMutation.ts
  hooks/useMap.ts
  pages/_app.tsx
  pages/index.tsx
  services/apis/todo.ts
  shared/types/todo.ts
  worker/index.ts
Labels: feature

#126 refactor: 디자인 명세에 맞게 create todo 변경
  components/index/Header/index.tsx
  components/index/Header/styles.tsx
  components/index/TodoSubmitForm/index.test.tsx
  components/index/TodoSubmitForm/index.tsx
  components/index/TodoSubmitForm/styles.tsx
  hooks/apis/todo/useTodoMutation.ts
  pages/index.tsx
  services/apis/todo.ts
Labels: feature

#127 feat: todo Location 저장된 위치로 기본 위치 설정
  components/index/MapModal/index.tsx
  components/index/TodoListItem/index.tsx
  hooks/useMap.ts
  pages/_app.tsx
  shared/types/location.ts
  shared/types/todo.ts
Labels: feature

#125 feat: TodoListItem에 contentEditable 적용
  components/common/ErrorBoundary/index.test.tsx
  components/index/MapModal/index.tsx
  components/index/TodoList/index.test.tsx
  components/index/TodoListItem/index.test.tsx
  components/index/TodoListItem/index.tsx
  components/index/TodoListItem/styles.tsx
  hooks/useContentEditable/index.test.tsx
  hooks/useContentEditable/index.ts
  hooks/useLocalForage/index.test.ts
  hooks/useOnClickOutside/index.test.ts
  jest.setup.js
  package.json
  pages/_app.tsx
  shared/utils/focus.ts
  shared/utils/testUtils.tsx
  testUtils.tsx
  yarn.lock
Labels: refactor, feature, test

#130 refactor: inbox page rendering optimization
  components/common/Sidebar/index.tsx
  components/index/Header/index.tsx
  components/index/TodoList/index.tsx
  components/index/TodoListItem/index.stories.tsx
  components/index/TodoListItem/index.test.tsx
  components/index/TodoListItem/index.tsx
  hooks/useContentEditable/index.ts
  pages/index.tsx
Labels: refactor

#135 feat: TodoList가 업데이트 되면 자동으로 IndexedDB에 저장
  components/index/TodoList/index.tsx
  shared/utils/localForage.ts
Labels: feature

#137 feat: pwa에 icon, manifest 적용
  .gitignore
  next.config.js
  pages/_app.tsx
  pages/_offline.tsx
  public/icon-512x512.png
  public/icon.png
  public/manifest.json
  worker/index.ts
Labels: feature

#139 feat: cache data using service worker
  worker/index.ts
Labels: feature

#140 feat: cache first, fallback to network (next static files)
  .gitignore
  next.config.js
  pages/index.tsx
  public/index.html
  worker/index.ts
Labels: feature

#141 feature: web push 구독 및 알림 받기
  pages/_app.tsx
  services/apis/webpush.ts
  shared/types/window.d.ts
  shared/utils/encryption.ts
  worker/index.ts
Labels: feature

#144 feat: 페이지와 서비스워커간의 통신 구현
  next.config.js
  pages/index.tsx
  shared/types/service-worker.d.ts
  worker/index.ts
Labels: feature

#145 style: SideBar 스타일 개선
  .eslintrc.js
  components/common/Figure/INBOX.tsx
  components/common/Figure/MAP.tsx
  components/common/Figure/TODAY.tsx
  components/common/Figure/styles.tsx
  components/common/Sidebar/SideBarMenu/index.tsx
  components/common/Sidebar/SideBarMenu/styles.tsx
  components/common/Sidebar/index.tsx
  components/common/Sidebar/styles.tsx
  pages/index.tsx
  public/assets/svgs/Area.svg
  public/assets/svgs/inbox.svg
  public/assets/svgs/location.svg
  public/assets/svgs/map.svg
  public/assets/svgs/today.svg
  public/assets/svgs/trash.svg
  public/assets/svgs/upcoming.svg
  shared/types/menu.ts
  styles/globalStyle.ts
Labels: style

#146 refactor: web push notification 모듈화
  pages/_app.tsx
  services/apis/webpush.ts
  services/webpush/todo.ts
  shared/api/apiClient.ts
  shared/api/todoApi.ts
  worker/index.ts
Labels: refactor

#148 chore: Next.js 환경 변수 적용
  .env
  .env.development
  .env.production
  .gitignore
Labels: chore

#151 fix: 장소 업데이트가 제대로 이루어지지 않는 버그 수정
  components/index/MapModal/index.tsx
  components/index/TodoList/index.tsx
Labels: bug

#150 feat: darkmode, toggle button 구현
  components/common/Sidebar/SideBarMenu/index.tsx
  components/common/Sidebar/SideBarMenu/styles.tsx
  components/common/Sidebar/styles.tsx
  components/index/Header/index.test.tsx
  components/index/Header/styles.tsx
  pages/_app.tsx
  pages/index.tsx
  shared/utils/testUtils.tsx
  styles/style.d.ts
  styles/theme.ts
Labels: chore, feature

#154 chore: 파일 정리 및 이름 재정의
  public/assets/svgs/area.svg
  shared/types/style.d.ts
Labels: chore

#156 fix: notification api end point update
  services/apis/webpush.ts
Labels: chore

#155 feat: TodoList 오프라인 동기화 구현
  components/index/TodoList/index.tsx
  components/index/TodoListItem/index.stories.tsx
  components/index/TodoListItem/index.test.tsx
  components/index/TodoListItem/index.tsx
  hooks/apis/todo/useTodoListQuery.ts
  hooks/apis/todo/useTodoMutation.ts
  package.json
  pages/_app.tsx
  pages/index.tsx
  shared/types/sync.ts
  shared/types/window.d.ts
  shared/utils/localForage.ts
  shared/utils/queryClient.ts
  shared/utils/testUtils.tsx
  store/forage/index.ts
  worker/index.ts
  yarn.lock
Labels: documentation, feature

#157 feat: sidebar 컴포넌트 _app에 적용 (모든 페이지)
  components/common/AppLayout/index.tsx
  components/common/AppLayout/styles.tsx
  pages/_app.tsx
  pages/index.tsx
  shared/constants/breakpoints.ts
  shared/utils/fetcher.ts
  store/sidebar/atom.ts
Labels: feature

#158 style: theme 변환시 transition 효과 적용
  components/common/Sidebar/SideBarMenu/styles.tsx
  components/common/Sidebar/index.tsx
  components/common/Sidebar/styles.tsx
  pages/index.tsx
  public/assets/svgs/mozi.svg
Labels: style

#161 feat: ESC 클릭시 TodoListItem에서 포커스 제거
  components/index/TodoListItem/index.tsx
Labels: feature

#166 feat: TodoService 오프라인 로직 추가
  hooks/apis/todo/useTodoMutation.ts
  package.json
  public/favicon.ico
  services/apis/todo.ts
  shared/types/todo.ts
  shared/utils/queryClient.ts
  yarn.lock
Labels: feature

#167 feat: options 버튼 추가
  components/common/Figure/ADD_CALENDAR.tsx
  components/common/Figure/ADD_DEADLINE.tsx
  components/common/Figure/ADD_PLACE.tsx
  components/common/Figure/ADD_TAG.tsx
  components/common/Figure/INBOX.tsx
  components/common/Figure/MAP.tsx
  components/common/Figure/TODAY.tsx
  components/index/MapModal/index.tsx
  components/index/MapModal/styles.tsx
  components/index/TodoListItem/index.tsx
  components/index/TodoListItem/styles.tsx
  public/assets/svgs/btn_add_calendar.svg
  public/assets/svgs/btn_add_deadline.svg
  public/assets/svgs/btn_add_place.svg
  public/assets/svgs/btn_add_tag.svg
  shared/types/figure.ts
Labels: feature

#169 feat: lighthouse ci 적용
  .github/workflows/lighthouse.yml
  .gitignore
  .lighthouserc.js
Labels: feature

#171 fix: push -> ci 실행하도록 변경
  .github/workflows/ci.yml
Labels: chore

#172 fix: develop branch에서 ci 실패
  .github/workflows/lighthouse.yml
Labels: bug

#173 feat: install lighthouse app
  .github/workflows/lighthouse.yml
Labels: chore, feature

#174 feat: TodoListItem 성능 최적화 및 오프라인 동기화 구현
  .gitignore
  components/common/Figure/CALENDAR.tsx
  components/common/Figure/DEADLINE.tsx
  components/common/Figure/PLACE.tsx
  components/common/Figure/TAG.tsx
  components/index/MapModal/index.tsx
  components/index/TodoList/index.test.tsx
  components/index/TodoList/index.tsx
  components/index/TodoListItem/index.stories.tsx
  components/index/TodoListItem/index.test.tsx
  components/index/TodoListItem/index.tsx
  pages/_app.tsx
  pages/index.tsx
  services/apis/todo.ts
  shared/constants/sync.ts
  shared/types/todo.ts
  shared/utils/fetcher.ts
  shared/utils/sync.ts
  worker/index.ts
Labels: refactor, feature, style

#175 style: 메모 추가 버튼
  components/common/Button/index.stories.tsx
  components/common/Button/index.tsx
  components/common/Button/styles.tsx
  components/index/Header/index.tsx
  components/index/Header/styles.tsx
  shared/types/style.d.ts
  styles/theme.ts
Labels: feature, style

#177 feat: nextauth를 사용한 카카오 로그인 구현
  package.json
  pages/_app.tsx
  pages/api/auth/[...nextauth].ts
  pages/login.tsx
  shared/types/environment.d.ts
  yarn.lock
Labels: documentation, feature

#178 style: sidebar & header
  components/common/AppLayout/index.tsx
  components/common/Figure/ARROWLEFT.tsx
  components/common/Figure/ARROWRIGHT.tsx
  components/common/Figure/HAMBURGER.tsx
  components/common/Figure/index.tsx
  components/common/Header/index.tsx
  components/common/Header/styles.tsx
  components/common/Sidebar/SideBarMenu/styles.tsx
  components/common/Sidebar/index.tsx
  components/common/Sidebar/styles.tsx
  components/index/Header/index.test.tsx
  components/index/Title/index.test.tsx
  components/index/Title/index.tsx
  components/index/Title/styles.tsx
  package.json
  pages/index.tsx
  public/assets/svgs/arrow_left.svg
  public/assets/svgs/arrow_right.svg
  public/assets/svgs/calendar.svg
  public/assets/svgs/deadline.svg
  public/assets/svgs/hamburger.svg
  public/assets/svgs/place.svg
  public/assets/svgs/tag.svg
  shared/types/style.d.ts
  store/sidebar/atom.ts
  styles/motion.ts
  styles/theme.ts
  yarn.lock
Labels: feature

#179 feat: 장소에 따라 알림
  components/index/MapModal/index.tsx
  components/index/TodoList/index.test.tsx
  components/index/TodoList/index.tsx
  components/index/TodoListItem/index.stories.tsx
  components/index/TodoListItem/index.tsx
  pages/index.tsx
  services/apis/alarm.ts
  services/apis/todo.ts
  shared/types/location.ts
  shared/types/todo.ts
  shared/utils/encryption.ts
  shared/utils/serialize.ts
  worker/index.ts
Labels: feature

#180 chore: fix figure props
  components/common/Figure/ARROWLEFT.tsx
  components/common/Figure/ARROWRIGHT.tsx
Labels: chore

#182 fix: todolistitem bug 수정
  components/index/TodoListItem/index.tsx
Labels: bug

#184 feat: 장소에 따라 알림 (#179)
  components/index/MapModal/index.tsx
  components/index/TodoList/index.test.tsx
  components/index/TodoList/index.tsx
  components/index/TodoListItem/index.stories.tsx
  components/index/TodoListItem/index.tsx
  pages/index.tsx
  services/apis/alarm.ts
  services/apis/todo.ts
  shared/types/location.ts
  shared/types/todo.ts
  shared/utils/encryption.ts
  shared/utils/fetcher.ts
  shared/utils/serialize.ts
  worker/index.ts
Labels: bug

#186 feat: 사용자는 체크 표시를 통해 할 일을 완료할 수 있다.
  components/index/TodoList/index.tsx
  components/index/TodoListItem/index.stories.tsx
  components/index/TodoListItem/index.test.tsx
  components/index/TodoListItem/index.tsx
  pages/index.tsx
  services/apis/todo.ts
  shared/types/todo.ts
  shared/utils/fetcher.ts
Labels: feature

#190 style: todo 컴포넌트 UI 스타일링
  components/index/MapModal/index.tsx
  components/index/MapModal/styles.tsx
  components/index/TodoListItem/index.test.tsx
  components/index/TodoListItem/index.tsx
  components/index/TodoListItem/styles.tsx
Labels: style

#193 refactor: backspace or delete 버튼으로 todo 삭제
  components/common/Sidebar/styles.tsx
  components/index/TodoListItem/index.tsx
  components/index/TodoListItem/styles.tsx
Labels: refactor

#191 style: sidebar html 구조 변경 및 디자인 시안 반영
  components/common/Figure/INBOX.tsx
  components/common/Figure/MAP.tsx
  components/common/Figure/TODAY.tsx
  components/common/Figure/TRASH.tsx
  components/common/Figure/UPCOMING.tsx
  components/common/Figure/index.tsx
  components/common/Sidebar/SideBarMenu/index.tsx
  components/common/Sidebar/SideBarMenu/styles.tsx
  components/common/Sidebar/index.tsx
  components/common/Sidebar/styles.tsx
  pages/today/index.tsx
  pages/trash/index.tsx
  pages/upcoming/index.tsx
  shared/types/figure.ts
  shared/types/style.d.ts
  styles/theme.ts
Labels: refactor, style

#200 style: inbox title
  components/index/Title/index.tsx
  components/index/Title/styles.tsx
Labels: style

#202 style: footer
  components/common/Figure/BOXARROWRIGHT.tsx
  components/common/Figure/BOXPLUS.tsx
  components/common/Figure/CALENDAR.tsx
  components/common/Figure/SEARCH.tsx
  components/common/Figure/index.tsx
  components/common/Footer/index.tsx
  components/common/Footer/styles.tsx
  pages/index.tsx
  public/assets/svgs/box_arrow_right.svg
  public/assets/svgs/box_plus.svg
  public/assets/svgs/calendar.svg
  public/assets/svgs/search.svg
Labels: style

#203 fix: figure calendar 이름 겹치는거 이름 수정
  components/common/Figure/CALENDAR.tsx
  components/common/Figure/FOOTERCALENDAR.tsx
  components/common/Figure/index.tsx
  components/common/Footer/index.tsx
  components/index/TodoListItem/index.tsx
  public/assets/svgs/calendar.svg
  public/assets/svgs/footer_calendar.svg
Labels: style

#206 chore: mozi assets
  public/favicon.ico
  public/icon-512x512.png
  public/icon.png
  public/logo.png
  public/logo512.png
  public/manifest.json
Labels: chore

#217 style: map page Layout
  components/common/Figure/SIDEBARARROWLEFT.tsx
  components/common/Sidebar/styles.tsx
  components/map/SearchInput/index.tsx
  components/map/SearchInput/styles.tsx
  pages/map/index.tsx
  public/assets/svgs/search.svg
  public/assets/svgs/sidebar_arrow_left.svg
  shared/types/style.d.ts
  styles/theme.ts
Labels: style

#219 feat: todo 개수 sidebar에 표시
  components/common/Sidebar/SideBarMenu/index.tsx
  components/common/Sidebar/index.tsx
  components/common/Sidebar/styles.tsx
  pages/index.tsx
  store/todo/atom.ts
Labels: feature

#220 feat: map searchbar 열고 닫는 기능 구현
  components/map/SearchInput/index.tsx
  components/map/SearchInput/styles.tsx
  pages/map/index.tsx
Labels: feature

#221 style: map 페이지 최근 검색어 UI
  components/map/RecentSearch/index.tsx
  components/map/RecentSearch/styles.tsx
  components/map/SearchSideBar/index.tsx
  components/map/SearchSideBar/styles.tsx
  pages/map/index.tsx
  styles/theme.ts
Labels: style

#222 feature: chips component
  components/common/Chip/index.stories.tsx
  components/common/Chip/index.tsx
  components/common/Chip/styles.tsx
  components/common/Figure/CALENDAR.tsx
  components/common/Figure/DEADLINE.tsx
  components/common/Figure/DELETE.tsx
  components/common/Figure/PLACE.tsx
  components/common/Figure/TAG.tsx
  public/assets/svgs/btn_delete.svg
  public/assets/svgs/tag.svg
Labels: feature

#223 feature: chip list
  components/common/Chip/index.tsx
  components/common/ChipList/Chip/index.stories.tsx
  components/common/ChipList/Chip/index.tsx
  components/common/ChipList/Chip/styles.tsx
  components/common/ChipList/index.stories.tsx
  components/common/ChipList/index.tsx
  components/common/ChipList/styles.tsx
  components/common/Figure/DEADLINE.tsx
  components/common/Figure/DELETE.tsx
  components/common/Figure/PLACE.tsx
  components/common/Figure/TAG.tsx
  public/assets/svgs/tag.svg
Labels: feature
