Repository team-yaza/mozi-client, pull requests merged in 2022-11, with the labels that each got.

#441 fix: map page에서 Todo를 만드는 경우 버그 수정
  src/hooks/apis/todo/useTodoMutation.ts
  src/services/apis/todo.ts
  src/worker/index.ts
Labels: bug

#438 refactor: useTodoListQuery 로직 통일 및 타입 추가
  src/hooks/apis/todo/useTodoListQuery.ts
  src/pages/index.tsx
  src/pages/map/index.tsx
  src/pages/trash/index.tsx
  src/pages/upcoming/index.tsx
  src/shared/constants/dialog.ts
  src/shared/types/common.ts
  src/shared/types/todo.ts
  src/worker/index.ts
Labels: refactor

#442 feat: Add Cypress Eslint Plugin
  cypress/.eslintrc.json
  cypress/support/commands.ts
  cypress/support/index.ts
  cypress/tsconfig.json
  package.json
  src/components/common/AppLayout/index.tsx
  src/shared/constants/application.ts
  tsconfig.json
  yarn.lock
Labels: chore

#444 fix: 컴포넌트 props가 바뀜에 따른 Storybook 빌드 에러
  src/components/common/TodoListItem/Description/index.stories.tsx
Labels: bug

#445 feat: add cypress ci
  .github/workflows/cypress.yml
  .gitignore
  cypress.config.ts
Labels: chore

#446 refactor: 장소가 바뀔때, 1분마다 Todo 체크
  src/pages/_app.tsx
  src/shared/constants/delay.ts
  src/shared/constants/serviceWorker.ts
  src/worker/index.ts
Labels: refactor

#449 feat: cypress login e2e test
  .github/workflows/cypress.yml
  README.md
  cypress.config.ts
  cypress/e2e/inbox.spec.ts
  cypress/e2e/login.spec.ts
  cypress/e2e/spec.cy.ts
  cypress/plugins/index.js
  cypress/support/commands.ts
  cypress/support/index.ts
  jest.config.js
  src/components/common/Sidebar/index.tsx
  src/pages/_app.tsx
  src/pages/inbox/index.tsx
  src/pages/index.tsx
  src/pages/kakao/index.tsx
  src/pages/login/index.tsx
  src/shared/constants/delay.ts
Labels: test

#450 fix: Cypress Login
  cypress.config.ts
Labels: bug, test

#453 refactor: todolistitem title 변경된 props를 storybook에도 적용
  README.md
  src/components/common/TodoListItem/Title/index.stories.tsx
Labels: refactor, chore

#454 refactor: queryKey
  src/hooks/apis/todo/useTodoListQuery.ts
  src/shared/constants/queryKey.ts
Labels: refactor

#455 refactor: todolist statistics
  src/components/common/AppLayout/index.tsx
  src/components/common/Sidebar/index.stories.tsx
  src/components/common/Sidebar/index.tsx
  src/hooks/apis/todo/useTodoListQuery.ts
  src/services/apis/todo.ts
  src/shared/constants/queryKey.ts
  src/shared/types/todo.ts
  src/shared/utils/sync.ts
  src/store/localForage/index.ts
Labels: refactor, feature

#456 refactor: Todo Check하는거 상태로 추가
  src/components/common/AppLayout/index.tsx
  src/components/common/TodoList/DraggableTodoList.tsx
  src/components/common/TodoList/index.tsx
  src/components/common/TodoListItem/index.stories.tsx
  src/components/common/TodoListItem/index.tsx
  src/components/common/TodoListItem/styles.tsx
  src/components/common/TodoListItem/unsafe_TodoListItem.tsx
  src/components/common/index.tsx
  src/hooks/apis/todo/useTodoMutation.ts
  src/pages/inbox/index.tsx
  src/pages/logbook/index.tsx
  src/pages/map/index.tsx
  src/pages/trash/index.tsx
Labels: refactor

#457 chore: legacy service 제거
  src/hooks/apis/todo/useTodoListQuery.ts
  src/hooks/apis/todo/useTodoMutation.ts
  src/services/apis/todo.ts
Labels: chore

#458 refactor: TodoList Mutation
  src/hooks/apis/todo/useTodoMutation.ts
  src/pages/inbox/index.tsx
  src/pages/logbook/index.tsx
  src/pages/map/index.tsx
  src/pages/trash/index.tsx
  src/pages/upcoming/index.tsx
  src/shared/types/todo.ts
Labels: refactor

#459 chore: 알람 관련 코드 주석
  src/pages/_app.tsx
Labels: chore

#460 refactor: checkbox image
  src/components/common/TodoListItem/Options/index.tsx
  src/components/common/TodoListItem/index.tsx
Labels: refactor

#461 refactor: useCallback 제거
  src/components/common/Chip/index.tsx
  src/components/common/SetLocationModal/index.tsx
  src/components/map/SearchSideBar/index.tsx
  src/pages/kakao/index.tsx
  src/pages/trash/index.tsx
Labels: refactor

#470 feat: TodoListItem에 대한 Skeleton UI 추가
  src/components/common/Skeleton/index.stories.tsx
  src/components/common/Skeleton/index.tsx
  src/components/common/Skeleton/styles.tsx
  src/components/common/TodoListItem/index.tsx
  src/components/common/index.tsx
  src/pages/inbox/index.tsx
  src/shared/utils/queryClient.ts
  src/store/localForage/index.ts
Labels: feature

#473 feat: SEO at _document.tsx
  public/assets/images/og-mozi.png
  src/components/common/SEO/index.tsx
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/pages/inbox/index.tsx
  src/pages/index.tsx
  src/pages/kakao/index.tsx
  src/pages/logbook/index.tsx
  src/pages/map/index.tsx
  src/pages/setting/index.tsx
  src/pages/trash/index.tsx
  src/pages/upcoming/index.tsx
  src/shared/constants/application.ts
Labels: feature

#474 feat: apple launch아이콘 추가
  public/apple-launch-828x1792.png
  src/pages/_document.tsx
Labels: refactor

#477 chore: 애플의 다양한 기기에서의 start-up 이미지 추가
  public/apple-icon-120x120.png
  public/apple-icon-152x152.png
  public/apple-icon-180x180.png
  public/apple-icon-192x192.png
  src/pages/_document.tsx
Labels: chore

#478 refactor: Cypress Login E2E test
  cypress/e2e/login.spec.ts
  cypress/support/commands.ts
  cypress/support/e2e.ts
Labels: refactor

#479 feat: Cypress E2E Test Inbox Page API Mocking
  cypress/e2e/inbox.spec.ts
  cypress/fixtures/todos.json
  src/components/common/Spinner/index.tsx
  src/styles/globalStyle.ts
Labels: feature

#484 chore: ci eslint github action 변경
  .github/workflows/ci.yml
  .github/workflows/eslint.yml
  cypress.config.ts
Labels: chore

#485 refactor: update request
  src/components/common/TodoListItem/index.tsx
  src/hooks/apis/todo/useTodoMutation.ts
  src/pages/trash/index.tsx
  src/services/apis/todo.ts
  src/shared/types/todo.ts
Labels: refactor

#487 chore: offline updated 변경된 API에 맞게 잘 작동하도록 수정
  src/services/apis/todo.ts
Labels: refactor

#488 refactor: Mutation Types
  .github/workflows/ci.yml
  src/hooks/apis/todo/useTodoListQuery.ts
  src/hooks/apis/todo/useTodoMutation.ts
  src/services/apis/todo.ts
  src/shared/types/todo.ts
Labels: refactor

#491 fix: 장소 검색 성능 향상
  src/components/map/SearchSideBar/index.tsx
  src/services/apis/location.ts
  src/shared/utils/map.ts
Labels: feature

#490 refactor: Calendar
  public/robots.txt
  src/components/common/CalendarModal/index.tsx
  src/components/common/Figure/NEXTARROW.tsx
  src/components/common/Figure/PREVARROW.tsx
  src/components/common/Title/index.tsx
  src/components/upcoming/Calendar/index.tsx
  src/components/upcoming/CalendarBody/index.tsx
  src/components/upcoming/CalendarBody/styles.tsx
  src/components/upcoming/CalendarHeader/index.tsx
  src/components/upcoming/CalendarHeader/styles.tsx
  src/components/upcoming/Navigator/index.tsx
  src/components/upcoming/Navigator/styles.tsx
  src/pages/temp.tsx
  src/pages/upcoming/index.tsx
  src/shared/types/style.d.ts
  src/shared/utils/date.ts
  src/styles/theme.ts
Labels: refactor, style

#493 docs: readme에 작성한 글 링크 추가
  README.md
  src/pages/upcoming/index.tsx
Labels: documentation

#494 refactor: offline update
  README.md
  src/pages/_app.tsx
  src/pages/inbox/index.tsx
  src/pages/upcoming/index.tsx
  src/shared/constants/application.ts
Labels: refactor

#497 feat: map 페이지 바운더리 추가
  src/pages/map/index.tsx
Labels: feature

#498 refactor: offline delete
  src/components/common/TodoList/DraggableTodoList.tsx
  src/components/common/TodoListItem/index.tsx
  src/pages/inbox/index.tsx
Labels: refactor

#500 feat: google calendar 연동
  .env
  .env.development
  .env.production
  src/pages/migrations/google.tsx
  src/pages/setting/index.tsx
Labels: feature

#501 style: google calendar 연동하기 버튼
  public/assets/svgs/google.svg
  src/components/common/AppLayout/index.tsx
  src/components/common/Figure/GOOGLE.tsx
  src/components/setting/LogoutButton/index.tsx
  src/pages/map/index.tsx
  src/pages/migrations/google.tsx
  src/pages/setting/index.tsx
Labels: style

#503 fix: 휴지통 비우기시 클라이언트 상태 업데이트하지 못하는 버그 수정
  src/hooks/apis/todo/useTodoMutation.ts
Labels: bug, refactor

#504 chore: 웹 접근성 개선
  public/manifest.json
  src/pages/index.tsx
Labels: chore

#505 feat: 사용자는 Map 페이지에서 현재 위치로 이동할 수 있다.
  public/assets/svgs/crosshairs.svg
  src/components/common/Figure/CROSSHAIRS.tsx
  src/components/common/Figure/index.tsx
  src/components/map/SetLocationModal/index.tsx
  src/pages/map/index.tsx
  src/shared/types/style.d.ts
  src/styles/theme.ts
  src/styles/utils.ts
Labels: feature

#506 fix: Input CLS
  src/components/common/TextInput/index.tsx
  src/components/map/SetLocationModal/index.tsx
Labels: refactor

#507 chore: Recoil 제거
  package.json
  src/components/common/Sidebar/index.tsx
  src/components/common/TextInput/index.stories.tsx
  src/components/map/SearchSideBar/index.tsx
  src/hooks/useSearchSideBar.ts
  src/hooks/useSideBar.ts
  src/pages/_app.tsx
  src/shared/utils/testUtils.tsx
  src/store/localStorage/sidebar.ts
  src/store/sidebar/atom.ts
  src/store/todo/atom.ts
  yarn.lock
Labels: chore

#509 style: alarm icon in todolistitem
  public/assets/svgs/alarm.svg
  src/components/common/Chip/index.stories.tsx
  src/components/common/Figure/ALARM.tsx
  src/components/common/Figure/DEADLINE.tsx
  src/components/common/Figure/PLACE.tsx
  src/components/common/Figure/index.tsx
  src/components/common/TodoListItem/Options/index.tsx
  src/components/common/TodoListItem/Options/styles.tsx
  src/shared/types/style.d.ts
  src/styles/theme.ts
Labels: style

#510 fix: inbox에서 드래그앤 드랍해서 Todo 삭제시 영구 삭제되는 버그 해결
  src/pages/inbox/index.tsx
Labels: bug, refactor

#511 fix: google authUrl 동적으로 받아오게 변경
  .env
  .env.development
  .env.production
  README.md
  src/components/common/AlarmModal/index.tsx
  src/components/common/TodoListItem/Options/styles.tsx
  src/pages/setting/index.tsx
Labels: documentation, style

#512 refactor: google calendar 동기화 에러처리
  src/pages/setting/index.tsx
  src/shared/constants/dialog.ts
Labels: refactor, feature

#513 feat: inbox 페이지에 대한 E2E 테스트
  README.md
  cypress/e2e/inbox.spec.ts
  cypress/fixtures/todos.json
  cypress/videos/inbox.spec.ts.mp4
  cypress/videos/login.spec.ts.mp4
  src/components/common/Chip/index.tsx
  src/components/common/Modal/index.tsx
  src/components/common/Modal/styles.tsx
  src/components/common/SetLocationModal/index.tsx
  src/components/common/TodoListItem/Description/index.tsx
  src/components/common/TodoListItem/Map/index.tsx
  src/components/common/TodoListItem/Options/index.tsx
  src/components/common/TodoListItem/index.tsx
  src/pages/map/index.tsx
  src/services/apis/todo.ts
Labels: feature, test

#514 style: Alarm Type Styling
  cypress/videos/inbox.spec.ts.mp4
  cypress/videos/login.spec.ts.mp4
  src/components/common/AlarmModal/index.tsx
  src/components/common/AlarmModal/styles.tsx
  src/components/common/TodoListItem/Options/index.tsx
Labels: style

#518 fix: Map 페이지에서 TodoList가 많아지면 화면에서 스크롤되지 않고 넘치는 현상
  README.md
  src/components/map/SearchSideBar/MapTodoList/styles.tsx
  src/components/map/SearchSideBar/index.tsx
  src/components/map/SearchSideBar/styles.tsx
Labels: style

#521 style: 캘린더 모달에서 화살표 svg가 잘 보이지 않았던 부분 수정
  src/components/common/CalendarModal/styles.tsx
  src/services/apis/todo.ts
Labels: style

#523 style: map page boundary 색상 변경
  src/pages/map/index.tsx
Labels: chore, style

#528 fix: Upcoming 사이드바 숫자가 올라가지 않는 현상
  README.md
  src/components/common/CalendarModal/index.tsx
  src/components/common/Sidebar/index.tsx
  src/hooks/apis/todo/useTodoListQuery.ts
  src/hooks/apis/todo/useTodoMutation.ts
  src/services/apis/todo.ts
Labels: bug

#529 fix: 드래그앤 드롭 복원 기능 동작하도록 구현
  src/pages/trash/index.tsx
Labels: refactor, feature

#531 style: upcoming footer
  src/components/common/Footer/styles.tsx
  src/components/common/Header/styles.tsx
  src/components/common/Title/styles.tsx
  src/components/upcoming/CalendarBody/styles.tsx
  src/components/upcoming/CalendarHeader/styles.tsx
  src/pages/upcoming/index.tsx
Labels: style

#534 style: 모바일에서 TodoListItem 내부의 아이콘이 보이지 않는 현상 제거
  src/components/common/Figure/CALENDAR.tsx
  src/components/common/Figure/DEADLINE.tsx
Labels: bug, style

#535 style: Chip 컴포넌트 다크모드 적용
  src/components/common/Chip/index.stories.tsx
  src/components/common/Chip/index.tsx
  src/components/common/Chip/styles.tsx
  src/components/common/Figure/DELETE.tsx
  src/components/common/TodoListItem/Options/index.tsx
  src/components/common/TodoListItem/Options/styles.tsx
  src/shared/types/style.d.ts
  src/styles/theme.ts
Labels: style

#536 style: Calendar에 다크모드 적용
  src/components/upcoming/CalendarBody/styles.tsx
  src/shared/types/style.d.ts
  src/styles/theme.ts
Labels: style

#537 feat: Todo에 알람타입, 거리타입 추가
  src/shared/types/todo.ts
Labels: feature

#542 fix: upcoming footer 올라오는 현상
  src/pages/upcoming/index.tsx
Labels: bug

#547 fix: navigation 링크 수정
  src/components/common/Footer/index.tsx
Labels: bug

#549 fix: safari 브라우저에서 svg 렌더링 잘 되지 않는 현상
  src/components/common/Figure/CALENDAR.tsx
  src/components/common/Figure/DEADLINE.tsx
  src/components/common/Figure/DELETE.tsx
  src/components/common/Figure/GOOGLE.tsx
  src/components/common/Figure/SETTING.tsx
  src/pages/setting/index.tsx
Labels: bug

#550 feat: 알림 모달에서 버튼 클릭시 표시
  src/components/common/AlarmModal/index.tsx
  src/components/common/AlarmModal/styles.tsx
Labels: feature

#551 style: DeadLine 빨간색으로 색깔 변경
  src/components/common/Chip/index.tsx
  src/components/common/Figure/DEADLINE.tsx
  src/components/common/TodoListItem/Options/index.tsx
Labels: style

#553 style: alarm modal margin 조정
  src/components/common/AlarmModal/styles.tsx
Labels: style

#554 test: 사용자는 원하는 장소를 검색할 수 있다.
  cypress/e2e/map.spec.ts
  src/components/map/SearchSideBar/index.tsx
  src/pages/map/index.tsx
Labels: test

#555 refactor: alarm, deadline 정보 표시
  src/components/upcoming/CalendarBody/index.tsx
  src/components/upcoming/CalendarBody/styles.tsx
Labels: refactor

#556 refactor: 사용자의 위치가 변할 때 잡아주는 API
  cypress/e2e/map.spec.ts
  src/pages/_app.tsx
  src/pages/map/index.tsx
Labels: refactor

#570 feat: distance type에 따라 바운더리 다르게 구현
  src/components/common/AlarmModal/index.tsx
  src/pages/map/index.tsx
  src/shared/types/todo.ts
Labels: feature
