Repository team-yaza/mozi-client, pull requests merged in 2022-10, with the labels that each got.

#312 feat: 최근 검색어 삭제 기능
  public/assets/svgs/cancel.svg
  src/components/common/Figure/CANCEL.tsx
  src/components/common/Figure/index.tsx
  src/components/map/SearchSideBar/RecentSearch/index.tsx
  src/components/map/SearchSideBar/RecentSearch/styles.tsx
  src/components/map/SearchSideBar/index.tsx
  src/components/map/SearchSideBar/styles.tsx
Labels: feature, style

#309 feat: 사용자는 Map 페이지에서 Todo를 생성할 수 있다.
  package.json
  scripts/init-letsencrypt.sh
  src/components/common/Modal/index.tsx
  src/components/common/Modal/styles.tsx
  src/components/common/SetLocationModal/index.tsx
  src/components/common/TodoListItem/Map/index.tsx
  src/components/common/TodoListItem/Map/styles.tsx
  src/components/common/TodoListItem/index.tsx
  src/components/map/SetLocationModal/index.tsx
  src/components/map/SetLocationModal/styles.tsx
  src/hooks/apis/todo/useTodoMutation.ts
  src/hooks/useNaverMap.ts
  src/hooks/useOnClickOutside/index.ts
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/pages/index.tsx
  src/pages/map/index.tsx
  src/shared/constants/delay.ts
  src/shared/types/style.d.ts
  src/shared/types/todo.ts
  src/styles/animation.ts
  src/styles/motion.ts
  src/styles/theme.ts
  tsconfig.json
  yarn.lock
Labels: refactor, feature, style

#313 docs: 모지 공식문서 사이트 추가
  README.md
Labels: documentation

#314 feat: 캘린더 모달 구현
  package.json
  public/assets/svgs/next_arrow.svg
  public/assets/svgs/prev_arrow.svg
  src/components/common/CalendarModal/index.stories.tsx
  src/components/common/CalendarModal/inedex.tsx
  src/components/common/CalendarModal/styles.tsx
  src/components/common/Figure/NEXTARROW.tsx
  src/components/common/Figure/PREVARROW.tsx
  src/components/common/Figure/index.tsx
  src/hooks/apis/todo/useTodoListQuery.ts
  src/shared/types/todo.ts
  src/shared/utils/date.ts
  src/shared/utils/dateToString.ts
  yarn.lock
Labels: bug, feature, style

#315 fix: useNaverMap side effect 제거
  src/components/common/TodoListItem/Map/index.tsx
  src/components/trash/Title/styles.tsx
  src/hooks/useNaverMap.ts
Labels: refactor

#317 refactor: useNaverMap hook
  src/components/common/TodoListItem/Map/index.tsx
  src/components/common/TodoListItem/Options/index.tsx
  src/hooks/useNaverMap.ts
  src/pages/map/index.tsx
Labels: refactor, chore

#318 fix: Inbox 항목을 많이 추가 후 맨 아래 할일 클릭시 하이라이트 안되는 버그
  .env
  src/components/common/TodoListItem/index.tsx
  src/pages/_app.tsx
Labels: bug, refactor

#319 style: 캘린더 모달 시간 알림을 위한 스타일링
  public/assets/svgs/stopwatch.svg
  src/components/common/CalendarModal/index.stories.tsx
  src/components/common/CalendarModal/index.tsx
  src/components/common/CalendarModal/styles.tsx
  src/components/common/Figure/STOPWATCH.tsx
  src/components/common/Figure/index.tsx
Labels: feature, style

#320 feat: common text input component
  package.json
  src/components/common/TextInput/index.stories.tsx
  src/components/common/TextInput/index.test.tsx
  src/components/common/TextInput/index.tsx
  src/components/common/TextInput/styles.tsx
  src/components/map/SetLocationModal/index.tsx
  src/shared/constants/input.ts
  yarn.lock
Labels: feature, style

#321 refactor: delete location modal
  src/components/common/AlertModal/index.stories.tsx
  src/components/common/AlertModal/index.tsx
  src/components/common/AlertModal/styles.tsx
  src/components/common/LocationDeleteDialog/index.tsx
  src/components/common/LocationDeleteDialog/styles.tsx
  src/components/common/Modal/styles.tsx
  src/components/common/ModalBackground/index.tsx
  src/components/common/ModalBackground/styles.tsx
  src/components/common/TodoListItem/Options/index.tsx
Labels: refactor

#322 refactor: useInput 훅을 사용한 글자 제한
  src/components/common/TextInput/index.tsx
  src/components/map/SetLocationModal/index.tsx
  src/hooks/useInput.ts
Labels: refactor

#323 feat: 마감일, 알람시간 아이콘에 따른 캘린더 모달 발생 구현
  src/components/common/CalendarModal/index.tsx
  src/components/common/CalendarModal/styles.tsx
  src/components/common/Figure/NEXTARROW.tsx
  src/components/common/Figure/PLACE.tsx
  src/components/common/Figure/PREVARROW.tsx
  src/components/common/TodoListItem/Options/index.tsx
Labels: feature

#324 feat: 사용자는 사이드바에서 Todo의 개수를 파악할 수 있다.
  src/components/common/Sidebar/SideBarMenu/index.tsx
  src/components/common/Sidebar/index.tsx
  src/hooks/apis/todo/useTodoListQuery.ts
  src/hooks/apis/todo/useTodoMutation.ts
  src/shared/types/todo.ts
Labels: feature

#325 feature: due date, alarm date 백엔드에 요청 보내기 구현
  src/components/common/CalendarModal/index.tsx
  src/components/common/TodoList/index.tsx
  src/components/common/TodoListItem/Options/index.tsx
  src/components/common/TodoListItem/index.tsx
  src/hooks/apis/todo/useTodoMutation.ts
  src/services/apis/todo.ts
  src/shared/types/todo.ts
  src/shared/utils/date.ts
Labels: feature

#326 feat: 등록된 마감일, 알림시간 데이터 삭제 기능 구현
  src/components/common/CalendarModal/index.tsx
  src/components/common/ChipList/index.stories.tsx
  src/components/common/ChipList/index.tsx
  src/components/common/ChipList/styles.tsx
  src/components/common/DeleteModal/index.tsx
  src/components/common/DeleteModal/styles.tsx
  src/components/common/LocationDeleteDialog/index.tsx
  src/components/common/TodoListItem/Options/index.tsx
Labels: refactor, feature

#327 feat: force delete Todo
  src/hooks/apis/todo/useTodoMutation.ts
  src/pages/trash/index.tsx
  src/services/apis/todo.ts
Labels: feature

#328 docs: 튜토리얼 추가
  README.md
Labels: documentation

#329 feat: Todo Drag And Drop 기능 (순서만)
  next.config.js
  package.json
  src/components/common/Footer/styles.tsx
  src/components/common/TodoList/DraggableTodoList.tsx
  src/components/common/TodoListItem/index.tsx
  src/pages/_app.tsx
  src/pages/index.tsx
  yarn.lock
Labels: feature

#331 fix: 장소 입력 안되는 버그
  src/components/TestComponent.tsx
  src/components/common/TodoListItem/index.tsx
Labels: bug, refactor

#332 feat: 사용자는 세팅 화면에서 화면 모드를 바꿀 수 있다.
  public/assets/svgs/setting.svg
  src/components/common/Figure/SETTING.tsx
  src/components/common/Figure/index.tsx
  src/components/common/Header/index.tsx
  src/components/common/Header/styles.tsx
  src/components/common/TodoListItem/index.tsx
  src/components/setting/Color/index.tsx
  src/components/setting/Color/styles.tsx
  src/components/setting/Theme/index.tsx
  src/components/setting/Theme/styles.tsx
  src/components/setting/Title/index.tsx
  src/components/setting/Title/styles.tsx
  src/pages/_app.tsx
  src/pages/setting/index.tsx
Labels: feature, style

#334 feat: useDoubleTap hook
  src/hooks/useDoubleTap/index.test.tsx
  src/hooks/useDoubleTap/index.ts
Labels: feature

#335 feat: Error Monitoring With Sentry
  .env
  .gitignore
  next.config.js
  package.json
  sentry.client.config.ts
  sentry.server.config.ts
  src/pages/_error.tsx
  src/pages/sentry_sample_error.tsx
  tsconfig.json
  yarn.lock
Labels: feature

#336 fix: sentry 설치 후 cd 안되는 버그
  .gitignore
  sentry.properties
Labels: bug

#338 feat: Upcomming 페이지 캘린더 컴포넌트 구현
  src/components/upcoming/Calendar/index.tsx
  src/components/upcoming/Calendar/styles.tsx
  src/components/upcoming/Title/index.tsx
  src/hooks/apis/todo/useTodoMutation.ts
  src/pages/upcoming/index.tsx
Labels: feature

#339 fix: service worker registration by sentry
  next.config.js
Labels: bug

#340 style: 카카오 로그인 대기화면에서 로딩 스피너 가운데로 배치
  src/pages/kakao/index.tsx
Labels: style

#341 feat: Common Button Component
  .storybook/preview.js
  src/components/common/Button/index.stories.tsx
  src/components/common/Button/index.tsx
  src/components/common/Button/styles.tsx
  src/components/common/Spinner/index.stories.tsx
Labels: feature

#342 feat: logout
  src/components/common/Button/index.tsx
  src/components/common/Button/styles.tsx
  src/components/setting/LogoutButton/index.tsx
  src/pages/setting/index.tsx
  src/shared/utils/cookie.ts
Labels: feature

#343 feat: DND를 활용한 할 일 삭제
  src/components/common/TodoListItem/index.tsx
  src/components/common/TodoListItem/styles.tsx
  src/pages/index.tsx
Labels: feature

#344 feat: 달력 클릭시 해당 날짜, 이후의 Todo 보이기
  src/components/upcoming/Calendar/index.tsx
  src/components/upcoming/Calendar/styles.tsx
  src/hooks/apis/todo/useTodoListQuery.ts
  src/pages/upcoming/index.tsx
  src/shared/utils/date.ts
Labels: feature

#345 feat: drop placeholder 공통 컴포넌트
  src/components/common/Chip/index.stories.tsx
  src/components/common/DropPlaceholder/index.stories.tsx
  src/components/common/DropPlaceholder/index.tsx
  src/components/common/DropPlaceholder/styles.tsx
  src/pages/index.tsx
Labels: feature

#346 feat: chromatic deployment(CD)
  .github/workflows/chromatic.yml
  package.json
  src/components/common/Sidebar/index.stories.tsx
  yarn.lock
Labels: feature

#347 refactor: DropPlaceholder in MainPage
  src/components/common/DropPlaceholder/index.tsx
  src/components/common/DropPlaceholder/styles.tsx
  src/pages/index.tsx
  src/pages/sentry_sample_error.tsx
Labels: feature

#348 feat: Common Title Component
  src/components/common/Title/index.stories.tsx
  src/components/common/Title/index.tsx
  src/components/common/Title/styles.tsx
  src/components/common/TodoList/styles.tsx
  src/components/logbook/Title/index.tsx
  src/components/logbook/Title/styles.tsx
  src/pages/index.tsx
  src/pages/logbook/index.tsx
  src/pages/today/index.tsx
  src/pages/upcoming/index.tsx
Labels: feature

#358 refactor: sidebar에서 data fetching로직 상위 컴포넌트로 이동
  src/components/common/AppLayout/index.tsx
  src/components/common/Sidebar/index.tsx
  src/components/common/Title/styles.tsx
Labels: refactor

#359 refactor: SideBar에서 Today 제거 및 Storybook 작성
  .storybook/main.js
  .storybook/preview.js
  README.md
  package.json
  src/components/common/AppLayout/index.tsx
  src/components/common/Sidebar/SideBarMenu/index.tsx
  src/components/common/Sidebar/index.stories.tsx
  src/components/common/Sidebar/index.tsx
  yarn.lock
Labels: refactor, style

#361 feat: SideBarMenu 컴포넌트 분리 (스토리북)
  src/components/common/Figure/MARKER.tsx
  src/components/common/Figure/SETTING.tsx
  src/components/common/Sidebar/SideBarMenu/index.stories.tsx
  src/components/common/Sidebar/SideBarMenu/index.tsx
  src/components/common/Sidebar/SideBarMenu/temp.tsx
  src/components/common/Sidebar/index.stories.tsx
Labels: feature

#362 refactor: sidebar menu with common component
  src/components/common/Figure/INBOX.tsx
  src/components/common/Figure/LOGBOOK.tsx
  src/components/common/Figure/MAP.tsx
  src/components/common/Figure/TRASH.tsx
  src/components/common/Figure/UPCOMING.tsx
  src/components/common/Sidebar/SideBarMenu/index.stories.tsx
  src/components/common/Sidebar/SideBarMenu/index.tsx
  src/components/common/Sidebar/SideBarMenu/styles.tsx
  src/components/common/Sidebar/SideBarMenu/temp.tsx
  src/components/common/Sidebar/index.tsx
  src/components/common/Sidebar/styles.tsx
  src/components/common/Title/styles.tsx
  src/components/trash/Title/styles.tsx
Labels: refactor

#364 feat: Profile 공통 컴포넌트
  package.json
  src/components/common/Profile/index.stories.tsx
  src/components/common/Profile/index.tsx
  src/components/common/Profile/styles.tsx
  src/components/common/Sidebar/index.tsx
  src/components/common/Sidebar/styles.tsx
Labels: style

#365 feat: 시간에 따른 푸시 알림 기능 구현
  src/components/common/CalendarModal/index.tsx
  src/components/upcoming/Calendar/index.tsx
  src/services/apis/todo.ts
  src/shared/utils/date.ts
  src/worker/index.ts
Labels: feature

#366 feat: map 페이지에서 Todo 추가 기능 구현
  src/hooks/apis/todo/useTodoMutation.ts
  src/pages/index.tsx
  src/pages/map/index.tsx
  src/services/apis/todo.ts
  src/shared/types/todo.ts
Labels: feature

#368 feat: SEO Component
  README.md
  src/components/common/DeleteModal/index.tsx
  src/components/common/SEO/index.tsx
  src/pages/_document.tsx
  src/pages/today/index.tsx
  src/pages/trash/index.tsx
Labels: documentation, feature

#369 feat: use_unsafe_todoListQuery
  src/components/today/Title/index.tsx
  src/components/today/Title/styles.tsx
  src/hooks/apis/todo/useTodoListQuery.ts
  src/pages/index.tsx
  src/shared/utils/queryClient.ts
  src/worker/index.ts
Labels: feature

#370 refacotor: caching 로직 분리
  src/hooks/apis/todo/useTodoListQuery.ts
  src/worker/cache.ts
  src/worker/index.ts
Labels: refactor

#371 feat: serviceworker에 관한 util 함수 작성 및 모듈화
  src/shared/utils/serviceWorker.ts
  src/shared/utils/sync.ts
Labels: feature

#372 feat: use_unsafe_createTodo
  src/hooks/apis/todo/useTodoListQuery.ts
  src/hooks/apis/todo/useTodoMutation.ts
  src/pages/index.tsx
  src/services/apis/todo.ts
  src/shared/utils/serviceWorker.ts
Labels: feature

#373 feat: use_unsafe_updateTodo
  src/hooks/apis/todo/useTodoMutation.ts
  src/pages/index.tsx
  src/services/apis/todo.ts
Labels: feature

#375 feat: sync 이벤트를 사용해 IndexedDB에서 DB로 데이터 동기화
  src/components/common/TodoList/DraggableTodoList.tsx
  src/components/common/TodoListItem/index.tsx
  src/components/map/SearchSideBar/index.tsx
  src/hooks/apis/todo/useTodoListQuery.ts
  src/hooks/apis/todo/useTodoMutation.ts
  src/pages/index.tsx
  src/services/apis/todo.ts
  src/shared/constants/serviceWorker.ts
  src/shared/constants/sync.ts
  src/shared/utils/serviceWorker.ts
  src/shared/utils/sync.ts
  src/worker/index.ts
Labels: feature

#380 feat: react-hot-toast 로그인 페이지에 적용
  package.json
  src/pages/_app.tsx
  src/pages/kakao/index.tsx
  src/shared/constants/dialog.ts
  src/shared/utils/focus.ts
  src/shared/utils/sync.ts
  src/shared/utils/testUtils.tsx
  src/shared/utils/toast.ts
  yarn.lock
Labels: feature

#381 refactor: 상수들에게 as const 키워드 붙이기
  src/shared/constants/breakpoints.ts
  src/shared/constants/delay.ts
  src/shared/constants/url.ts
  src/shared/utils/kakao.ts
  src/styles/media.ts
Labels: refactor

#382 chore: production에서 sync가 동작하지 않는 상황에 대한 콘솔 확인
  public/index.html
  src/pages/kakao/index.tsx
  src/shared/utils/getCurrentPosition.ts
  src/shared/utils/sync.ts
Labels: chore

#384 refactor: export common components
  src/components/common/index.tsx
  src/hooks/apis/todo/useTodoMutation.ts
  src/pages/index.tsx
  src/pages/logbook/index.tsx
  src/pages/login/index.tsx
  src/pages/map/index.tsx
  src/pages/setting/index.tsx
  src/pages/upcoming/index.tsx
  src/services/apis/todo.ts
  src/store/localForage/index.ts
  src/worker/index.ts
Labels: chore

#386 style: Footer
  package.json
  src/components/common/Button/index.stories.tsx
  src/components/common/CalendarModal/index.stories.tsx
  src/components/common/Chip/index.stories.tsx
  src/components/common/DropPlaceholder/index.stories.tsx
  src/components/common/Figure/BOXARROWRIGHT.tsx
  src/components/common/Figure/BOXPLUS.tsx
  src/components/common/Figure/FOOTERCALENDAR.tsx
  src/components/common/Figure/SEARCH.tsx
  src/components/common/Footer/index.stories.tsx
  src/components/common/Footer/index.tsx
  src/components/common/Footer/styles.tsx
  src/components/common/Profile/index.stories.tsx
  src/components/common/SetLocationModal/index.stories.tsx
  src/components/common/Sidebar/SideBarMenu/index.stories.tsx
  src/components/common/Sidebar/index.stories.tsx
  src/components/common/Spinner/index.stories.tsx
  src/components/common/TextInput/index.stories.tsx
  src/components/common/Title/index.stories.tsx
  src/worker/index.ts
  yarn.lock
Labels: style

#387 style: header 스타일링 및 적용해야할 페이지에 적용
  src/components/common/Header/index.stories.tsx
  src/components/common/Header/styles.tsx
  src/components/common/Title/styles.tsx
  src/pages/index.tsx
  src/pages/logbook/index.tsx
  src/pages/map/index.tsx
  src/pages/trash/index.tsx
  src/pages/upcoming/index.tsx
  src/styles/theme.ts
Labels: feature

#388 feat: todo 생성시 index 부여해서 생성
  .github/pull_request_template.md
  src/hooks/apis/todo/useTodoListQuery.ts
  src/pages/kakao/index.tsx
  src/services/apis/todo.ts
  src/shared/constants/dialog.ts
  src/store/localForage/index.ts
Labels: feature

#389 feat: Drag And Drop을 통해 Todo의 index를 바꿀 수 있다.
  src/hooks/apis/todo/useTodoMutation.ts
  src/pages/index.tsx
  src/services/apis/todo.ts
  src/shared/constants/dialog.ts
  src/shared/types/todo.ts
  src/shared/utils/serviceWorker.ts
Labels: feature

#392 style: LogBook, Trash에 Footer 적용
  public/manifest.json
  src/pages/logbook/index.tsx
  src/pages/trash/index.tsx
Labels: feature

#395 style: header의 높이 모든 페이지에서 맞게 수정
  src/components/common/TodoList/styles.tsx
  src/pages/logbook/index.tsx
Labels: style

#396 style: sidebar border right
  src/components/common/Sidebar/styles.tsx
Labels: style

#397 refactor: SEO Component
  public/manifest.json
  src/components/common/SEO/index.tsx
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/shared/constants/application.ts
Labels: refactor, feature

#399 chore: 모든 페이지에 title 태그 정의
  src/components/common/Header/styles.tsx
  src/pages/kakao/index.tsx
  src/pages/logbook/index.tsx
  src/pages/login/index.tsx
  src/pages/setting/index.tsx
  src/pages/trash/index.tsx
  src/pages/upcoming/index.tsx
Labels: chore

#400 refactor: Setting Page Title 공통 컴포넌트로 바꿈
  src/components/setting/Title/index.tsx
  src/components/setting/Title/styles.tsx
  src/pages/kakao/index.tsx
  src/pages/setting/index.tsx
Labels: refactor, style

#401 feat: Footer의 각 아이콘에 기능 적용
  src/components/common/Footer/index.tsx
  src/pages/index.tsx
  src/pages/logbook/index.tsx
  src/pages/trash/index.tsx
  src/shared/constants/dialog.ts
Labels: feature

#402 fix: dropplaceholder absolute 속성줘서 감추기
  src/components/common/DropPlaceholder/styles.tsx
Labels: style

#403 fix: sidebar에서inbox에 제대로 focus되지 않는 부분 수정
  src/components/common/Sidebar/index.tsx
Labels: style

#404 refactor: TodoListItem Title Component
  src/components/common/TodoListItem/Title/index.stories.tsx
  src/components/common/TodoListItem/Title/index.tsx
  src/components/common/TodoListItem/Title/styles.tsx
  src/components/common/TodoListItem/index.stories.tsx
  src/components/common/TodoListItem/temp.tsx
  src/pages/_app.tsx
  src/pages/_document.tsx
Labels: bug, refactor, style

#406 refactor: TodoListItem Description Component
  src/components/common/TodoList/styles.tsx
  src/components/common/TodoListItem/Description/index.stories.tsx
  src/components/common/TodoListItem/Description/index.tsx
  src/components/common/TodoListItem/Description/styles.tsx
  src/components/common/TodoListItem/Title/index.tsx
  src/components/common/TodoListItem/Title/styles.tsx
  src/components/common/TodoListItem/index.tsx
  src/components/common/TodoListItem/styles.tsx
Labels: refactor, style

#408 feat: 사용자는 Drag And Drop을 통해 Todo를 삭제할 수 있다.
  src/pages/index.tsx
  src/pages/login/index.tsx
Labels: refactor, feature

#410 refactor: Chip Component
  src/components/common/Chip/index.stories.tsx
  src/components/common/Chip/index.tsx
  src/components/common/Chip/styles.tsx
  src/components/common/Figure/CALENDAR.tsx
  src/components/common/Figure/PLACE.tsx
  src/components/common/TodoListItem/Options/index.tsx
  src/components/common/TodoListItem/Options/styles.tsx
  src/components/common/TodoListItem/index.tsx
  src/components/common/TodoListItem/styles.tsx
Labels: refactor, style

#412 refactor: 맵 페이지 모달에서 todo title도 함께 작성할 수 있도록 구현
  src/components/common/SetLocationModal/index.stories.tsx
  src/components/common/SetLocationModal/index.tsx
  src/components/common/SetLocationModal/styles.tsx
  src/components/common/TodoListItem/Map/index.tsx
  src/components/map/SetLocationModal/index.tsx
  src/components/map/SetLocationModal/styles.tsx
  src/hooks/apis/todo/useTodoMutation.ts
  src/pages/map/index.tsx
  src/services/apis/todo.ts
  src/shared/types/todo.ts
  src/worker/index.ts
Labels: refactor

#413 style: Footer Component Dark Mode 적용
  src/components/common/Figure/BOXARROWRIGHT.tsx
  src/components/common/Figure/BOXPLUS.tsx
  src/components/common/Footer/styles.tsx
  src/pages/_app.tsx
  src/shared/types/style.d.ts
  src/styles/theme.ts
Labels: style

#415 refactor: 최근 검색어 기능을 검색바 클릭시 보이도록 구현
  src/components/map/SearchSideBar/RecentSearch/index.tsx
  src/components/map/SearchSideBar/RecentSearch/styles.tsx
  src/components/map/SearchSideBar/index.tsx
Labels: refactor

#414 style: SideBar DarkMode
  src/components/common/Footer/styles.tsx
  src/components/common/Sidebar/styles.tsx
  src/shared/types/style.d.ts
  src/styles/theme.ts
Labels: style

#417 feat: 맵 페이지 사이드바에 지도 내부에 있는 Todo 보이는 기능 구현
  src/components/map/SearchSideBar/MapTodoList/index.tsx
  src/components/map/SearchSideBar/MapTodoList/styles.tsx
  src/components/map/SearchSideBar/index.tsx
  src/hooks/useNaverMap.ts
  src/pages/map/index.tsx
Labels: feature

#418 refactor: 다른 navermap hook에서 안쓰이는 부분 나누기
  src/hooks/useNaverMap.ts
  src/pages/map/index.tsx
Labels: refactor

#419 style: Title및 TodoListItem Background Dark Mode 적용
  src/components/common/Header/styles.tsx
  src/components/common/Title/styles.tsx
  src/components/common/TodoListItem/styles.tsx
  src/shared/types/style.d.ts
  src/styles/theme.ts
Labels: style

#420 style: TodoListItem Description 컴포넌트에 다크모드 적용
  src/components/common/TodoListItem/Description/index.tsx
  src/components/common/TodoListItem/Description/styles.tsx
  src/components/index/Title/index.test.tsx
  src/components/index/Title/index.tsx
  src/components/index/Title/styles.tsx
Labels: style

#421 refactor: location util functions
  src/hooks/location/useLocation.ts
  src/hooks/useLocationRef.ts
  src/pages/_app.tsx
  src/shared/utils/getDistance.ts
  src/shared/utils/sync.ts
  src/worker/index.ts
Labels: refactor

#423 feat: 마커 핀을 클릭하면 해당 Todo의 Title 확인하는 기능
  src/pages/map/index.tsx
Labels: feature

#424 docs: 기술스택 사진 update
  README.md
Labels: chore

#426 fix: icon이 안보이는 버그 수정
  README.md
  src/components/common/DropPlaceholder/styles.tsx
  src/components/common/TodoListItem/Options/styles.tsx
Labels: documentation, style

#427 refactor: TodoListItem
  src/components/common/TodoList/DraggableTodoList.tsx
  src/components/common/TodoListItem/Options/styles.tsx
  src/components/common/TodoListItem/index.stories.tsx
  src/components/common/TodoListItem/styles.tsx
  src/components/common/TodoListItem/temp.tsx
  src/components/common/TodoListItem/unsafe_TodoListItem.tsx
  src/shared/types/todo.ts
  src/stories/Button.stories.tsx
  src/stories/Button.tsx
  src/stories/Header.stories.tsx
  src/stories/Header.tsx
  src/stories/Introduction.stories.mdx
  src/stories/Page.stories.tsx
  src/stories/Page.tsx
  src/stories/assets/code-brackets.svg
  src/stories/assets/colors.svg
  src/stories/assets/comments.svg
  src/stories/assets/direction.svg
  src/stories/assets/flow.svg
  src/stories/assets/plugin.svg
  src/stories/assets/repo.svg
  src/stories/assets/stackalt.svg
  src/stories/button.css
  src/stories/header.css
  src/stories/page.css
Labels: refactor, feature

#428 style: 모든 페이지 백그라운드에 Darkmode transition 효과 적용
  src/pages/logbook/index.tsx
  src/pages/map/index.tsx
  src/pages/setting/index.tsx
  src/pages/trash/index.tsx
  src/pages/upcoming/index.tsx
Labels: style

#430 refactor: 사용자의 위치를 가져오는 함수를 브라우저에 내장된 기능으로 리팩터링
  src/hooks/useLocationRef.ts
  src/pages/_app.tsx
  src/services/apis/todo.ts
  src/shared/constants/dialog.ts
  src/shared/constants/serviceWorker.ts
  src/shared/utils/location.ts
  src/shared/utils/serviceWorker.ts
Labels: refactor

#432 style: Map 페이지 Searchbar에 Darkmode 적용
  src/components/common/Figure/CANCEL.tsx
  src/components/map/SearchSideBar/MapTodoList/styles.tsx
  src/components/map/SearchSideBar/RecentSearch/styles.tsx
  src/components/map/SearchSideBar/styles.tsx
  src/shared/types/style.d.ts
  src/styles/theme.ts
  src/worker/index.ts
Labels: style

#433 feat: 휴지통 비우기 기능 (sync with serviceWorker)
  src/components/common/TodoList/index.tsx
  src/hooks/apis/todo/useTodoListQuery.ts
  src/hooks/apis/todo/useTodoMutation.ts
  src/pages/upcoming/index.tsx
  src/services/apis/todo.ts
  src/shared/types/todo.ts
  src/worker/index.ts
Labels: refactor, feature

#434 refactor(!): react-query
  src/components/common/CalendarModal/index.tsx
  src/components/common/DeleteModal/index.tsx
  src/components/common/TodoList/DraggableTodoList.tsx
  src/components/common/TodoList/index.tsx
  src/components/common/TodoListItem/Description/index.tsx
  src/components/common/TodoListItem/Map/index.tsx
  src/components/common/TodoListItem/Options/index.tsx
  src/components/common/TodoListItem/Title/index.tsx
  src/components/common/TodoListItem/index.tsx
  src/components/common/TodoListItem/unsafe_TodoListItem.tsx
  src/components/map/SearchSideBar/MapTodoList/index.tsx
  src/components/map/SearchSideBar/index.tsx
  src/hooks/apis/todo/useTodoMutation.ts
  src/pages/logbook/index.tsx
  src/pages/map/index.tsx
  src/pages/trash/index.tsx
  src/services/apis/todo.ts
Labels: refactor

#436 refactor: delete unnecessary useCallback
  src/components/common/DeleteModal/index.tsx
  src/components/common/Footer/index.tsx
  src/components/common/Modal/index.tsx
Labels: refactor

#437 refactor: useTodoListQuery
  src/hooks/apis/todo/useTodoListQuery.ts
  src/shared/constants/routes.ts
Labels: refactor
