Repository team-yaza/mozi-client, pull requests merged in 2022-09, with the labels that each got.

#224 style: Login Page
  components/common/Sidebar/index.tsx
  components/common/Sidebar/styles.tsx
  components/map/SearchSideBar/index.tsx
  pages/login.tsx
  pages/login/index.tsx
  public/assets/svgs/flying_mozi.svg
  public/assets/svgs/kakao.svg
  styles/theme.ts
Labels: style

#227 feat: useNaverMap hook
  components/map/SearchSideBar/RecentSearch/index.tsx
  components/map/SearchSideBar/RecentSearch/styles.tsx
  components/map/SearchSideBar/index.tsx
  components/map/SearchSideBar/styles.tsx
  hooks/useMap.ts
  hooks/useNaverMap.ts
  pages/_app.tsx
  pages/_document.tsx
  pages/map/index.tsx
  store/todo/atom.ts
Labels: feature

#228 feat: 지도에서 검색 기능 구현
  components/common/Figure/index.tsx
  components/common/Sidebar/index.tsx
  components/map/SearchSideBar/index.tsx
  components/map/SearchSideBar/styles.tsx
  pages/map/index.tsx
  shared/utils/map.ts
Labels: feature

#229 feature: todo options 시각화 구현
  components/common/ChipList/Chip/index.stories.tsx
  components/common/ChipList/Chip/index.tsx
  components/common/ChipList/Chip/styles.tsx
  components/common/ChipList/index.stories.tsx
  components/common/ChipList/index.tsx
  components/common/Figure/TODOTAG.tsx
  components/common/Figure/index.tsx
  components/index/TodoListItem/index.tsx
  components/index/TodoListItem/styles.tsx
  components/index/TodoMap/index.tsx
  components/index/TodoMap/styles.tsx
  public/assets/svgs/todoTag.svg
Labels: feature

#230 feat: NextPageLayout
  components/common/Sidebar/index.tsx
  components/common/Sidebar/styles.tsx
  pages/_app.tsx
  pages/index.tsx
  pages/login/index.tsx
  pages/map/index.tsx
  shared/types/environment.d.ts
Labels: refactor, feature

#233 feat: kakao login and sync with database with prisma
  package.json
  pages/_app.tsx
  pages/api/auth/[...nextauth].ts
  pages/login/index.tsx
  prisma/index.ts
  prisma/schema.prisma
  services/apis/todo.ts
  yarn.lock
Labels: refactor, feature

#231 feat: 지도를 클릭할 때 마커 생성
  .env
  components/common/Figure/MARKER.tsx
  components/common/Figure/index.tsx
  hooks/useNaverMap.ts
  pages/map/index.tsx
  public/assets/svgs/marker.svg
  styles/globalStyle.ts
Labels: feature, style

#239 feat: kakao login with no libraries
  components/common/Auth/index.tsx
  hooks/useCookie.ts
  middleware.ts
  package.json
  pages/_app.tsx
  pages/_document.tsx
  pages/api/auth/[...nextauth].ts
  pages/index.tsx
  pages/kakao/index.tsx
  pages/login/index.tsx
  shared/constants/kakao.ts
  shared/types/window.d.ts
  shared/utils/fetcher.ts
  shared/utils/kakao.ts
  yarn.lock
Labels: documentation, refactor, feature

#241 feat: get nearbysearch list in map page
  components/map/SearchSideBar/index.tsx
  services/apis/location.ts
  shared/utils/location.ts
  shared/utils/map.ts
Labels: feature

#242 docs: update readme
  README.md
Labels: documentation

#244 feat: 할 일 추가시 위에서 부터 추가
  pages/index.tsx
Labels: feature

#251 style: TodoListItem 스타일링
  components/index/TodoList/index.test.tsx
  components/index/TodoListItem/index.test.tsx
  components/index/TodoListItem/index.tsx
  components/index/TodoListItem/styles.tsx
  public/assets/svgs/check.svg
  shared/types/style.d.ts
  styles/theme.ts
Labels: refactor, style

#252 feat: debounce function
  shared/utils/debounce/index.test.ts
  shared/utils/debounce/index.ts
Labels: feature, test

#253 fix: TodoCalendar 이름, main background color to white
  components/index/TodoCalendar/index.tsx
  components/index/TodoCalendar/styles.tsx
  components/index/TodoListItem/index.tsx
  components/index/TodoListItem/styles.tsx
  styles/theme.ts
Labels: refactor, style

#254 fix: 더블 클릭시 Description 렌더링 안되는 버그
  components/index/TodoListItem/index.tsx
  pages/index.tsx
Labels: bug, refactor

#255 feat: Trash 페이지 비우는 버튼
  components/trash/Title/index.tsx
  components/trash/Title/styles.tsx
Labels: feature

#259 feat: Loading Spinner
  .gitignore
  components/common/Figure/LOGO.tsx
  components/common/Figure/index.tsx
  components/common/Spinner/index.stories.tsx
  components/common/Spinner/index.tsx
  components/common/Spinner/styles.tsx
  package.json
  pages/kakao/index.tsx
  public/assets/svgs/logo.svg
  yarn.lock
Labels: feature

#132 feat: dockerfile 적용
  .gitignore
  Dockerfile
  docker-compose.yml
  init-letsencrypt.sh
  nginx/nginx.conf
Labels: feature

#261 feat: CD with docker in AWS EC2
  .github/workflows/cd.yml
  docker-compose.yml
Labels: feature

#260 feat: Trash 페이지에 새로운 TodoListItem 컴포넌트 제작
  components/index/TodoListItem/index.tsx
  components/index/TodoListItem/styles.tsx
  components/trash/Title/styles.tsx
  components/trash/TodoList/index.tsx
  components/trash/TodoList/styles.tsx
  components/trash/TodoListItem/index.tsx
  components/trash/TodoListItem/styles.tsx
  hooks/useInputRef.ts
  package.json
  pages/trash/index.tsx
  services/apis/todo.ts
  yarn.lock
Labels: refactor, feature, style

#263 style: TodoListItem open transition 구현
  components/trash/TodoList/styles.tsx
  components/trash/TodoListItem/styles.tsx
Labels: feature, style

#264 feat: cookie를 활용한 login page로의 redirection
  middleware.ts
  package.json
  pages/_app.tsx
  pages/kakao/index.tsx
  shared/utils/cookie.ts
  shared/utils/fetcher.ts
  yarn.lock
Labels: refactor, feature

#265 feat: 휴지통 비우기 기능 추가
  components/trash/Title/index.tsx
  hooks/apis/todo/useTodoMutation.ts
  pages/trash/index.tsx
  services/apis/todo.ts
Labels: feature

#266 feat: 방향키로 TodoListItem의 focused 상태를 변경할 수 있도록 변경
  components/trash/TodoList/index.tsx
  components/trash/TodoListItem/index.tsx
  components/trash/TodoListItem/styles.tsx
Labels: refactor, feature

#268 fix: naver, kakao 관련 js 파일 캐시하지 않도록 변경
  worker/index.ts
Labels: refactor, feature

#269 fix: check를 누를 때 todolistitem이 focus되는 현상 수정
  components/index/TodoListItem/index.tsx
Labels: bug

#270 chore: kakao login production url 수정
  pages/kakao/index.tsx
  shared/utils/kakao.ts
Labels: chore

#271 fix: cookie 저장 방법 수정
  pages/kakao/index.tsx
Labels: feature

#272 feat: Todo focusing 상태에서 Enter 누르면 열리도록 변경
  components/index/TodoListItem/index.tsx
  components/index/TodoListItem/styles.tsx
Labels: feature

#275 docs: Create LICENSE
  LICENSE
Labels: documentation

#276 feat: 검색 결과를 클릭하면 지도의 중앙이 결과로 이동하고 마킹 표시를 한다.
  components/map/SearchSideBar/index.tsx
  components/map/SearchSideBar/styles.tsx
  hooks/useNaverMap.ts
  pages/map/index.tsx
Labels: feature

#281 docs: readme에 figma 디자인 링크 추가
  README.md
Labels: documentation

#279 refactor: TodoListItem 컴포넌트 리팩터링
  components/common/Auth/index.tsx
  components/common/Figure/PLACE.tsx
  components/common/Figure/TRASH.tsx
  components/common/Figure/styles.tsx
  components/common/Spinner/styles.tsx
  components/index/TodoListItem/index.tsx
  components/trash/Title/styles.tsx
  components/trash/TodoList/index.tsx
  components/trash/TodoList/styles.tsx
  components/trash/TodoListItem/Description/index.tsx
  components/trash/TodoListItem/Description/styles.tsx
  components/trash/TodoListItem/Map/index.tsx
  components/trash/TodoListItem/Map/styles.tsx
  components/trash/TodoListItem/Title/index.tsx
  components/trash/TodoListItem/Title/styles.tsx
  components/trash/TodoListItem/index.tsx
  components/trash/TodoListItem/styles.tsx
  hooks/apis/todo/useTodoMutation.ts
  hooks/useNaverMap.ts
  pages/trash/index.tsx
Labels: refactor, feature

#282 fix: mozi.cz에서 로그인시 localhost로 가는 버그 수정
  .dockerignore
  .github/workflows/cd.yml
  pages/kakao/index.tsx
Labels: bug

#284 feat: 최근 검색어 기능을 통해 더 쉽게 검색할 수 있다.
  components/map/SearchSideBar/RecentSearch/index.tsx
  components/map/SearchSideBar/index.tsx
  pages/map/index.tsx
  shared/types/location.ts
  store/localStorage/index.ts
  store/sidebar/atom.ts
Labels: documentation, feature

#285 docs: 서비스 소개 설명 추가
  README.md
Labels: documentation

#286 feat: 최근 검색어를 클릭해도 지도에서 이동할 수 있다.
  components/map/SearchSideBar/RecentSearch/index.tsx
  components/map/SearchSideBar/index.tsx
Labels: feature

#288 style: 지도 검색 부분 스타일링
  components/common/Figure/SEARCHPLACE.tsx
  components/common/Figure/index.tsx
  components/map/SearchSideBar/index.tsx
  components/map/SearchSideBar/styles.tsx
  public/assets/svgs/search_place.svg
Labels: style

#289 fix: client에서 카카오 로그인이 잘 안되는 버그 수정
  .github/workflows/cd.yml
  pages/kakao/index.tsx
Labels: bug

#290 feat: useSoftDeletedTodoList
  hooks/apis/todo/useTodoListQuery.ts
  pages/trash/index.tsx
  shared/types/todo.ts
Labels: feature

#291 feat: React Query를 사용한 오프라인 동기화
  components/trash/TodoListItem/index.tsx
  hooks/apis/todo/useTodoListQuery.ts
  hooks/apis/todo/useTodoMutation.ts
  hooks/useCookie.ts
  hooks/useNaverMap.ts
  pages/index.tsx
  services/apis/todo.ts
  shared/utils/queryClient.ts
  shared/utils/sync.ts
  worker/index.ts
Labels: refactor, feature

#292 feat: Todo 관련 컴포넌트를 common으로 이동
  components/common/TodoList/index.tsx
  components/common/TodoList/styles.tsx
  components/common/TodoListItem/Description/index.tsx
  components/common/TodoListItem/Description/styles.tsx
  components/common/TodoListItem/Map/index.tsx
  components/common/TodoListItem/Map/styles.tsx
  components/common/TodoListItem/Title/index.tsx
  components/common/TodoListItem/Title/styles.tsx
  components/common/TodoListItem/index.tsx
  components/common/TodoListItem/styles.tsx
  hooks/apis/todo/useTodoMutation.ts
  pages/_app.tsx
  pages/index.tsx
  pages/trash/index.tsx
  services/apis/todo.ts
Labels: refactor, feature

#294 feat: handle react query devtools in production
  package.json
  src/pages/_app.tsx
  src/shared/types/window.d.ts
  tsconfig.json
  yarn.lock
Labels: feature

#295 feat: inbox에서 done이 아닌 항목만 출력
  src/components/common/TodoListItem/index.tsx
  src/hooks/apis/todo/useTodoListQuery.ts
  src/hooks/apis/todo/useTodoMutation.ts
  src/services/apis/todo.ts
Labels: feature

#296 feat: Logbook을 활용해서 완료한 Todo를 관리할 수 있다.
  public/assets/svgs/logbook.svg
  src/components/common/Figure/LOGBOOK.tsx
  src/components/common/Figure/index.tsx
  src/components/common/Sidebar/SideBarMenu/index.tsx
  src/components/common/TodoListItem/index.tsx
  src/components/logbook/Title/index.tsx
  src/components/logbook/Title/styles.tsx
  src/hooks/apis/todo/useTodoListQuery.ts
  src/pages/logbook/index.tsx
Labels: feature, style

#297 feat: map에 사용자가 등록한 TodoList 보여주기
  src/hooks/apis/todo/useTodoListQuery.ts
  src/pages/map/index.tsx
  src/shared/types/todo.ts
Labels: refactor, feature

#298 feat: Todo 내부 장소 좌표 정보 수정 기능
  .storybook/preview.js
  public/assets/svgs/mozi_string.svg
  src/components/common/SetLocationModal/index.stories.tsx
  src/components/common/SetLocationModal/index.tsx
  src/components/common/SetLocationModal/styles.tsx
  src/components/common/TodoList/index.tsx
  src/components/common/TodoListItem/Map/index.tsx
  src/components/common/TodoListItem/Map/styles.tsx
  src/components/common/TodoListItem/index.tsx
  src/hooks/useNaverMap.ts
  src/shared/types/location.ts
  src/shared/types/todo.ts
Labels: feature

#300 chore: merge 되는 경우만 CD
  .github/workflows/cd.yml
Labels: chore

#299 feat: recoil-persist를 사용한 사이드바 상태 기억
  package.json
  src/components/common/Sidebar/index.tsx
  src/components/map/SearchSideBar/index.tsx
  src/hooks/useSearchSideBar.ts
  src/hooks/useSideBar.ts
  src/store/localStorage/sidebar.ts
  src/store/sidebar/atom.ts
  yarn.lock
Labels: feature

#302 feat: 장소이름 입력받는 모달 기능 구현
  package.json
  src/components/common/ModalBackground/index.tsx
  src/components/common/ModalBackground/styles.tsx
  src/components/common/Portal/index.tsx
  src/components/common/SetLocationModal/index.tsx
  src/components/common/SetLocationModal/styles.tsx
  src/components/common/Sidebar/index.tsx
  src/components/common/TodoListItem/Map/index.tsx
  src/components/common/TodoListItem/index.tsx
  src/components/map/SearchSideBar/index.tsx
  src/hooks/apis/todo/useTodoMutation.ts
  src/hooks/useOnClickOutside/index.test.ts
  src/hooks/useOnClickOutside/index.ts
  src/pages/_document.tsx
  src/services/apis/todo.ts
  src/shared/types/todo.ts
  yarn.lock
Labels: refactor, feature

#303 feat: todo에서 장소 정보 확인 기능 구현
  package.json
  public/assets/svgs/confirmButton.svg
  src/components/common/Chip/index.stories.tsx
  src/components/common/Chip/index.tsx
  src/components/common/Chip/styles.tsx
  src/components/common/ChipList/index.stories.tsx
  src/components/common/ChipList/index.tsx
  src/components/common/Figure/CONFIRMBUTTON.tsx
  src/components/common/Figure/index.tsx
  src/components/common/TodoListItem/Map/index.tsx
  src/components/common/TodoListItem/Map/styles.tsx
  src/components/common/TodoListItem/Options/index.tsx
  src/components/common/TodoListItem/Options/styles.tsx
  src/components/common/TodoListItem/index.tsx
  src/components/common/TodoListItem/styles.tsx
  src/components/index/TodoListItem/index.tsx
  src/hooks/useNaverMap.ts
  src/hooks/useOnClickOutside/index.ts
  yarn.lock
Labels: feature

#305 fix: lighthouse ci develop에 push될 때만 체크하도록 변경
  .github/workflows/lighthouse.yml
Labels: chore

#304 docs: readme 기술 스택 및 노션 링크 업데이트
  README.md
Labels: documentation

#307 feat: 등록된 장소 삭제
  src/components/common/AlertModal/index.stories.tsx
  src/components/common/AlertModal/index.tsx
  src/components/common/AlertModal/styles.tsx
  src/components/common/Chip/index.tsx
  src/components/common/SetLocationModal/index.tsx
  src/components/common/TodoListItem/Map/index.tsx
  src/components/common/TodoListItem/Options/index.tsx
  src/components/common/TodoListItem/index.tsx
  src/shared/types/todo.ts
Labels: feature

#308 refactor: 장소에 대한 알림 리팩토링
  src/components/common/Figure/CONFIRMBUTTON.tsx
  src/components/index/TodoCalendar/index.tsx
  src/components/index/TodoCalendar/styles.tsx
  src/components/index/TodoList/index.test.tsx
  src/components/index/TodoList/index.tsx
  src/components/index/TodoList/styles.tsx
  src/components/index/TodoListItem/index.stories.tsx
  src/components/index/TodoListItem/index.test.tsx
  src/components/index/TodoListItem/index.tsx
  src/components/index/TodoListItem/styles.tsx
  src/components/index/TodoMap/index.tsx
  src/components/index/TodoMap/styles.tsx
  src/hooks/useMap.ts
  src/pages/_app.tsx
  src/pages/index.tsx
  src/services/apis/todo.ts
  src/shared/types/location.ts
  src/shared/types/todo.ts
  src/shared/utils/serialize.ts
  src/store/todo/atom.ts
  src/worker/index.ts
Labels: refactor, feature
